"""add index

Revision ID: acbb07b5acc5
Revises: 7e67788356aa
Create Date: 2025-09-18 14:50:39.773679

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'acbb07b5acc5'
down_revision: Union[str, Sequence[str], None] = '7e67788356aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movies_genres'), 'movies', ['genres'], unique=False)
    op.create_index(op.f('ix_movies_keywords'), 'movies', ['keywords'], unique=False)
    op.create_index(op.f('ix_movies_popularity'), 'movies', ['popularity'], unique=False)
    op.create_index(op.f('ix_movies_production_countries'), 'movies', ['production_countries'], unique=False)
    op.create_index(op.f('ix_movies_spoken_languages'), 'movies', ['spoken_languages'], unique=False)
    op.create_index(op.f('ix_movies_vote_average'), 'movies', ['vote_average'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_vote_average'), table_name='movies')
    op.drop_index(op.f('ix_movies_spoken_languages'), table_name='movies')
    op.drop_index(op.f('ix_movies_production_countries'), table_name='movies')
    op.drop_index(op.f('ix_movies_popularity'), table_name='movies')
    op.drop_index(op.f('ix_movies_keywords'), table_name='movies')
    op.drop_index(op.f('ix_movies_genres'), table_name='movies')
    # ### end Alembic commands ###
